# stubs/lvgl/__init__.pyi
# Type stubs for lv_micropython LVGL bindings.
# Covers the subset of the API used by WaveformPy.
# Full LVGL API: https://docs.lvgl.io/master/

from typing import Any, Callable, Optional

# ── Constants ─────────────────────────────────────────────────────────────────

RADIUS_CIRCLE: int

class OPA:
    TRANSP: int
    COVER: int
    @staticmethod
    def __call__(val: int) -> int: ...

class ALIGN:
    TOP_MID: int
    TOP_LEFT: int
    TOP_RIGHT: int
    BOTTOM_MID: int
    BOTTOM_LEFT: int
    BOTTOM_RIGHT: int
    CENTER: int
    LEFT_MID: int
    RIGHT_MID: int

class PART:
    MAIN: int
    INDICATOR: int
    KNOB: int
    SELECTED: int
    ITEMS: int
    SCROLLBAR: int

class EVENT:
    CLICKED: int
    PRESSED: int
    RELEASED: int
    LONG_PRESSED: int
    VALUE_CHANGED: int
    GESTURE: int
    ALL: int

class ANIM:
    ON: int
    OFF: int

class DIR:
    LEFT: int
    RIGHT: int
    TOP: int
    BOTTOM: int
    HOR: int
    VER: int
    ALL: int

class INDEV_TYPE:
    POINTER: int
    KEYPAD: int
    ENCODER: int
    BUTTON: int

class INDEV_STATE:
    PRESSED: int
    RELEASED: int

class COLOR_FORMAT:
    RGB565: int
    RGB888: int
    ARGB8888: int
    NATIVE: int

class DISPLAY_RENDER_MODE:
    PARTIAL: int
    DIRECT: int
    FULL: int

# ── Fonts ─────────────────────────────────────────────────────────────────────

class font_t: ...

font_montserrat_12: font_t
font_montserrat_14: font_t
font_montserrat_16: font_t
font_montserrat_18: font_t
font_montserrat_20: font_t
font_montserrat_22: font_t
font_montserrat_24: font_t
font_montserrat_28: font_t
font_montserrat_32: font_t
font_montserrat_36: font_t
font_montserrat_40: font_t
font_montserrat_44: font_t
font_montserrat_48: font_t

# ── Color ─────────────────────────────────────────────────────────────────────

class color_t:
    full: int

def color_make(r: int, g: int, b: int) -> color_t: ...
def color_hex(val: int) -> color_t: ...
def color_white() -> color_t: ...
def color_black() -> color_t: ...

class palette_t:
    RED: int
    BLUE: int
    GREEN: int
    YELLOW: int
    ORANGE: int
    GREY: int

class palette:
    @staticmethod
    def main(p: int) -> color_t: ...
    @staticmethod
    def lighten(p: int, lvl: int) -> color_t: ...
    @staticmethod
    def darken(p: int, lvl: int) -> color_t: ...

# ── Geometry ──────────────────────────────────────────────────────────────────

class point_t:
    x: int
    y: int
    def __init__(self, d: dict[str, int]) -> None: ...

class area_t:
    x1: int
    y1: int
    x2: int
    y2: int

# ── Base object ───────────────────────────────────────────────────────────────

class obj:
    class FLAG:
        HIDDEN: int
        CLICKABLE: int
        SCROLLABLE: int
        SCROLL_ELASTIC: int
        FLOATING: int

    def __init__(self, parent: Optional["obj"] = None) -> None: ...
    def set_size(self, w: int, h: int) -> None: ...
    def set_width(self, w: int) -> None: ...
    def set_height(self, h: int) -> None: ...
    def set_pos(self, x: int, y: int) -> None: ...
    def set_x(self, x: int) -> None: ...
    def set_y(self, y: int) -> None: ...
    def align(self, align: int, x_ofs: int = 0, y_ofs: int = 0) -> None: ...
    def align_to(self, base: "obj", align: int, x_ofs: int = 0, y_ofs: int = 0) -> None: ...
    def center(self) -> None: ...
    def add_flag(self, flag: int) -> None: ...
    def clear_flag(self, flag: int) -> None: ...
    def has_flag(self, flag: int) -> bool: ...
    def add_event_cb(self, cb: Callable, event: int, user_data: Any) -> None: ...
    def remove_event_cb(self, cb: Callable) -> None: ...
    def set_style_bg_color(self, color: color_t, selector: int) -> None: ...
    def set_style_bg_opa(self, opa: int, selector: int) -> None: ...
    def set_style_border_color(self, color: color_t, selector: int) -> None: ...
    def set_style_border_width(self, w: int, selector: int) -> None: ...
    def set_style_border_opa(self, opa: int, selector: int) -> None: ...
    def set_style_radius(self, r: int, selector: int) -> None: ...
    def set_style_pad_all(self, pad: int, selector: int) -> None: ...
    def set_style_pad_top(self, pad: int, selector: int) -> None: ...
    def set_style_pad_bottom(self, pad: int, selector: int) -> None: ...
    def set_style_pad_left(self, pad: int, selector: int) -> None: ...
    def set_style_pad_right(self, pad: int, selector: int) -> None: ...
    def set_style_text_color(self, color: color_t, selector: int) -> None: ...
    def set_style_text_font(self, font: font_t, selector: int) -> None: ...
    def set_style_text_align(self, align: int, selector: int) -> None: ...
    def del_async(self) -> None: ...
    def get_width(self) -> int: ...
    def get_height(self) -> int: ...
    def get_x(self) -> int: ...
    def get_y(self) -> int: ...

# ── Widgets ───────────────────────────────────────────────────────────────────

class label(obj):
    class LONG:
        WRAP: int
        DOT: int
        SCROLL: int
        SCROLL_CIRCULAR: int
        CLIP: int

    class TEXT_ALIGN:
        LEFT: int
        CENTER: int
        RIGHT: int
        AUTO: int

    def __init__(self, parent: Optional[obj] = None) -> None: ...
    def set_text(self, text: str) -> None: ...
    def set_text_fmt(self, fmt: str, *args: Any) -> None: ...
    def get_text(self) -> str: ...
    def set_long_mode(self, mode: int) -> None: ...
    def set_recolor(self, en: bool) -> None: ...

class bar(obj):
    def __init__(self, parent: Optional[obj] = None) -> None: ...
    def set_range(self, min_val: int, max_val: int) -> None: ...
    def set_value(self, val: int, anim: int) -> None: ...
    def get_value(self) -> int: ...

class btn(obj):
    def __init__(self, parent: Optional[obj] = None) -> None: ...

class canvas(obj):
    def __init__(self, parent: Optional[obj] = None) -> None: ...
    def set_buffer(self, buf: Any, w: int, h: int, cf: int) -> None: ...
    def fill_bg(self, color: color_t, opa: int) -> None: ...
    def draw_line(self, points: list[point_t], width: int, color: color_t, opa: int) -> None: ...
    def draw_rect(self, x: int, y: int, w: int, h: int, dsc: Any) -> None: ...
    def draw_text(self, x: int, y: int, max_w: int, dsc: Any, txt: str) -> None: ...

class qrcode(obj):
    def __init__(self, parent: Optional[obj] = None,
                 size: int = 200,
                 light_color: Optional[color_t] = None,
                 dark_color: Optional[color_t] = None) -> None: ...
    def update(self, data: bytes, data_len: int = -1) -> None: ...

class arc(obj):
    def __init__(self, parent: Optional[obj] = None) -> None: ...
    def set_range(self, min_val: int, max_val: int) -> None: ...
    def set_value(self, val: int) -> None: ...
    def set_angles(self, start: int, end: int) -> None: ...
    def set_bg_angles(self, start: int, end: int) -> None: ...
    def set_rotation(self, rotation: int) -> None: ...

class line(obj):
    def __init__(self, parent: Optional[obj] = None) -> None: ...
    def set_points(self, points: list[point_t], point_num: int) -> None: ...

class slider(obj):
    def __init__(self, parent: Optional[obj] = None) -> None: ...
    def set_range(self, min_val: int, max_val: int) -> None: ...
    def set_value(self, val: int, anim: int) -> None: ...
    def get_value(self) -> int: ...

class switch(obj):
    def __init__(self, parent: Optional[obj] = None) -> None: ...
    def add_state(self, state: int) -> None: ...
    def clear_state(self, state: int) -> None: ...

class spinner(obj):
    def __init__(self, parent: Optional[obj] = None, time: int = 1000, arc_len: int = 60) -> None: ...

# ── Input device ──────────────────────────────────────────────────────────────

class indev_t:
    def set_type(self, t: int) -> None: ...
    def set_read_cb(self, cb: Callable) -> None: ...
    def get_gesture_dir(self) -> int: ...
    def get_point(self) -> point_t: ...

class indev_data_t:
    point: point_t
    state: int
    key: int

def indev_create() -> indev_t: ...
def indev_active() -> Optional[indev_t]: ...

# ── Display ───────────────────────────────────────────────────────────────────

class display_t:
    def set_flush_cb(self, cb: Callable) -> None: ...
    def set_draw_buffers(self, buf1: Any, buf2: Optional[Any]) -> None: ...
    def set_render_mode(self, mode: int) -> None: ...
    def set_color_format(self, fmt: int) -> None: ...
    def set_resolution(self, w: int, h: int) -> None: ...
    def flush_ready(self) -> None: ...

def display_create(w: int, h: int) -> display_t: ...
def draw_buf_create(w: int, h: int, cf: int, flags: int) -> Any: ...

# ── Screen management ─────────────────────────────────────────────────────────

def scr_load(scr: obj) -> None: ...
def scr_load_anim(scr: obj, anim: int, time: int, delay: int, auto_del: bool) -> None: ...
def scr_act() -> obj: ...
def layer_top() -> obj: ...
def layer_sys() -> obj: ...

# ── Lifecycle ─────────────────────────────────────────────────────────────────

def init() -> None: ...
def deinit() -> None: ...
def tick_inc(tick_period: int) -> None: ...
def timer_handler() -> int: ...
def task_handler() -> int: ...
