# stubs/uos.pyi - MicroPython uos stubs

from typing import Any, Iterator

def listdir(path: str = ".") -> list[str]: ...
def mkdir(path: str) -> None: ...
def rmdir(path: str) -> None: ...
def remove(path: str) -> None: ...
def rename(old_path: str, new_path: str) -> None: ...
def stat(path: str) -> tuple: ...
def statvfs(path: str) -> tuple: ...
def getcwd() -> str: ...
def chdir(path: str) -> None: ...
def mount(device: Any, mount_point: str, *, readonly: bool = False) -> None: ...
def umount(mount_point: str) -> None: ...

def ilistdir(path: str = ".") -> Iterator[tuple[str, int, int, int]]: ...
