# stubs/urequests.pyi - MicroPython urequests stubs

from typing import Any, Optional

class Response:
    status_code: int
    text: str
    content: bytes
    def json(self) -> Any: ...
    def close(self) -> None: ...

def get(url: str, **kwargs: Any) -> Response: ...
def post(url: str, data: Any = None, json: Any = None, **kwargs: Any) -> Response: ...
def put(url: str, data: Any = None, **kwargs: Any) -> Response: ...
def delete(url: str, **kwargs: Any) -> Response: ...
def head(url: str, **kwargs: Any) -> Response: ...
def request(method: str, url: str, **kwargs: Any) -> Response: ...
