# stubs/network/__init__.pyi - MicroPython network module stubs

from typing import Optional

STA_IF: int
AP_IF: int

class WLAN:
    def __init__(self, interface_id: int) -> None: ...
    def active(self, is_active: Optional[bool] = None) -> bool: ...
    def connect(self, ssid: str, password: str = "") -> None: ...
    def disconnect(self) -> None: ...
    def isconnected(self) -> bool: ...
    def ifconfig(self) -> tuple[str, str, str, str]: ...
    def scan(self) -> list[tuple]: ...
    def status(self) -> int: ...
    def config(self, param: str = "", **kwargs: object) -> object: ...
