# stubs/machine/__init__.pyi - MicroPython machine module stubs

from typing import Any, Callable, Optional

def freq(hz: Optional[int] = None) -> int: ...
def reset() -> None: ...
def deepsleep(time_ms: int = 0) -> None: ...
def lightsleep(time_ms: int = 0) -> None: ...
def reset_cause() -> int: ...
def unique_id() -> bytes: ...

class Pin:
    IN: int
    OUT: int
    OPEN_DRAIN: int
    PULL_UP: int
    PULL_DOWN: int
    IRQ_RISING: int
    IRQ_FALLING: int
    def __init__(self, id: int, mode: int = IN, pull: int = -1, value: int = -1) -> None: ...
    def value(self, v: Optional[int] = None) -> int: ...
    def on(self) -> None: ...
    def off(self) -> None: ...
    def irq(self, handler: Callable, trigger: int) -> None: ...

class I2C:
    def __init__(self, id: int, *, scl: Pin, sda: Pin, freq: int = 400000) -> None: ...
    def scan(self) -> list[int]: ...
    def readfrom(self, addr: int, nbytes: int) -> bytes: ...
    def writeto(self, addr: int, buf: bytes) -> int: ...
    def readfrom_mem(self, addr: int, memaddr: int, nbytes: int) -> bytes: ...
    def writeto_mem(self, addr: int, memaddr: int, buf: bytes) -> None: ...

class SoftI2C(I2C):
    def __init__(self, *, scl: Pin, sda: Pin, freq: int = 100000) -> None: ...

class SPI:
    def __init__(self, id: int, *, baudrate: int = 1000000, polarity: int = 0,
                 phase: int = 0, sck: Optional[Pin] = None,
                 mosi: Optional[Pin] = None, miso: Optional[Pin] = None) -> None: ...
    def read(self, nbytes: int, write: int = 0) -> bytes: ...
    def write(self, buf: bytes) -> None: ...
    def write_readinto(self, write_buf: bytes, read_buf: bytearray) -> None: ...

class I2S:
    RX: int
    TX: int
    MONO: int
    STEREO: int
    def __init__(self, id: int, *, sck: Pin, ws: Pin, sd: Pin,
                 mode: int, bits: int, format: int, rate: int, ibuf: int) -> None: ...
    def readinto(self, buf: bytearray) -> int: ...
    def write(self, buf: bytes) -> int: ...
    def deinit(self) -> None: ...

class SDCard:
    def __init__(self, slot: int = 1, *, clk: Optional[Pin] = None,
                 cmd: Optional[Pin] = None, data0: Optional[Pin] = None) -> None: ...

class Timer:
    PERIODIC: int
    ONE_SHOT: int
    def __init__(self, id: int = -1) -> None: ...
    def init(self, *, period: int = -1, mode: int = PERIODIC,
             callback: Optional[Callable] = None) -> None: ...
    def deinit(self) -> None: ...

class RTC:
    def __init__(self) -> None: ...
    def datetime(self, datetimetuple: Optional[tuple] = None) -> tuple: ...
