[platformio]
build_dir = /Users/matthewmorrone/Projects/Arduino/Waveshare/.pio-central/Spectrum/${PIOENV}
libdeps_dir = /Users/matthewmorrone/Projects/Arduino/Waveshare/.pio-central/libdeps
src_dir = ..
include_dir = Spectrum

[env:spectrum_usb]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.37/platform-espressif32.zip
board = esp32-s3-devkitc-1
framework = arduino

board_build.mcu = esp32s3
board_build.f_cpu = 240000000L
board_upload.flash_size = 16MB
board_build.partitions = default_16MB.csv
board_build.arduino.memory_type = qio_opi

upload_speed = 460800
monitor_speed = 115200

lib_extra_dirs = /Users/matthewmorrone/Projects/Arduino/libraries
lib_ldf_mode = deep+

lib_deps =
  kosme/arduinoFFT
  adafruit/Adafruit GFX Library

build_flags =
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DBOARD_HAS_PSRAM
  -mfix-esp32-psram-cache-issue
  -I Spectrum
  -I ../Shared

build_src_filter =
  +<Spectrum/spectrum.cpp>
  +<Shared/es8311.c>
